import { authSocketMiddleware } from '../helpers/jwt.js';
import loggers from './logger.js';
import client from './redis.js';
import { Server } from 'socket.io';
import { createAdapter } from '@socket.io/redis-adapter';
import { insertDocument } from './mongo.js';
let socketIO;
var sockets = {};
export const socketRedis = (server)=>{
    const socks = new Server(server, {
        // transports:[
        //     'websocket'
        //   ],
        cors: {
          origin: "*"
        }
      });
    const pubClient = client;
    const subClient = pubClient.duplicate();
    
    socks.adapter(createAdapter(pubClient, subClient));
    
    // socks.listen(3000);
    
    
    
    return socks;
    
    }
export const socketConnection = (server, app) => {
    socketIO = new Server(server, {
        cors: {
          origin: '*'
        }
      });
    // socketIO = socketRedis(server);
    socketIO.on('connection', (socket) => {
        const user = { socketC: socket };
        console.log(`⚡: ${socket.id} user just connected!`);
        // socket.join(socket.id)
        socket.on('connected', (userId) => {
            console.log('IDS',userId);
            sockets[userId] = socket.id;
            // Save the socket id to Redis so that all processes can access it.
            client.hmset('mastersocket', sockets, function(err) {
                if (err) {
                    throw err;
                }
                console.log(`Master socket is now${  socket.id}`);
            });
            console.log('UserIddd', userId);
            // The socket ID is stored along with the unique ID generated by the client
            app.set('sockets', sockets);

            //sockets.push(socket.id);
            console.log('socks', sockets);
            // console.log('socks users', getSocketUser());
            // The sockets object is stored in Express so it can be grabbed in a route
        });
        socket.on('success', (data) => {
            console.log('tttttttttttttttttttfyj', data.username);
            socket.broadcast.emit('login', data);
        });
        socket.on('disconnect', () => {
            console.log('🔥: A user disconnected:');
            delete sockets[socket.id];
        });
        socket.on('Shutdown', () => {
            //exit(0);
        });
        socket.on('disconnected', (id) => {
            console.log(': A user disconnected' + id);
            delete sockets[socket.id];
            if (id) {
              client.hdel('mastersocket', [id ? id : 9], function (err) {
                if (err) {
                  throw err;
                }
                // client.hdel('loggedinip', [userid ? userid : 9], function (err) {
                //   if (err) {
                //     throw err;
                //   }
                // });
              });
            }
          });
        socket.on('loading',(data)=>{
            console.log('Loading....',data)
        })
        socket.on('billingError',(data)=>{
            console.log('Error....', data);
            socket.broadcast.emit('errorBill', data);
            loggers.error('Billing error', {
                ...data
            })
        })
        socket.on('dashboard',(data)=>{
            console.log('Dashboard of:',data)
        })
        socket.on('billing',(data)=>{
            console.log('Billing of:', data)
            socket.broadcast.emit('bill', data);
        })
         socket.on('api',async(data)=>{
             console.log('API of:', data)
             await insertDocument(data)
            //   loggers.error('API error', {
            //     ...data
            // })
        })
        socket.on('print',(data)=>{
            console.log('Print of:',data)
        })
      
        socket.on('error', function(err) {
            console.log("Socket.IO Error");
            console.log(err.stack); // this is changed from your code in last comment
        });
// Join a specific room based on Device ID
    socket.on('join-room', (roomId) => {
        socket.join(roomId);
    });

    // Forward control commands (clicks/swipes) to Android
    socket.on('control-command', (data) => {
        socketIO.to(data.roomId).emit('execute-command', data);
    });
    socket.on('screen-frame', (data) => {
    socketIO.to(data.roomId).emit('screen-frame', data);
    });
    // Forward WebRTC signaling data
    socket.on('signal', (data) => {
        socketIO.to(data.roomId).emit('signal', data);
    });
    });
    // socketIO.use((socket, next) => {
    //     authSocketMiddleware(socket, next);
    // })
    app.set("io", socketIO);
    app.set('sockets', sockets);


    return socketIO;
};
export const getSocketIo = () => {
    return socketIO;
};

export const getSocketUser = (fn) => {
    // return sockets;
    client.hgetall('mastersocket', (err, obj) => {
        if (err) {
            throw err;
        }
        console.log('DEDIS', obj);
        fn(obj);
    });
};
export const notifyAll = (data) => {
    console.log(data);
    socketIO.socket.on('course', data);
};
